# Site settings
title: Gameful Design
email: peacemotion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This site is a kind of blog to document my work in the course Gameful Design.
baseurl: "/gameful-design" # the subpath of your site, e.g. /blog/
url: "http://peacememories.github.io/" # the base hostname & protocol for your site
twitter_username: liveag
github_username:  peacememories

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/page:num/"
