# Site settings
title: Gameful Design
email: peacemotion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
	This site is a kind of blog to document my work in the course Gameful Design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: liveag
github_username:  peacememories

# Build settings
markdown: kramdown
